apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: app
spec:
  imagePullSecrets: []
  containers:
    - name: http-server
      image: ghcr.io/damlys/phpdock
      imagePullPolicy: Never
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      env:
        - name: PHP_OPCACHE_ENABLE
          value: "false"
      #command: []
      #args: []
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: 250m
          memory: 256M
        limits:
          cpu: 1000m
          memory: 1G
