apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    useDockerCLI: true
    push: false
  artifacts:
    - image: ghcr.io/damlys/phpdock
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
#          - src: ./etc/Caddyfile
#            dest: /etc/caddy/Caddyfile
#          - src: ./etc/php-fpm.conf
#            dest: /usr/local/etc/php-fpm.d/php-fpm.conf
#          - src: ./etc/php.ini
#            dest: /usr/local/etc/php/conf.d/php.ini
#          - src: ./etc/xdebug.ini
#            dest: /usr/local/etc/php/conf.d/xdebug.ini
          - src: app/**/*
            dest: /app
            strip: app
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - ./k8s/pod.yaml
portForward:
  - namespace: default
    resourceType: pod
    resourceName: app
    port: 8080
    localPort: 38080
