apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: app
spec:
  containers:
    - name: app
      image: ghcr.io/damlys/phpdock
      env:
        - name: PHP_OPCACHE_ENABLE
          value: "false"
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      ports:
        - containerPort: 8080
          protocol: TCP
