version: "3.8"
services:
  app:
    environment:
      OPCACHE_ENABLE: "off"
      XDEBUG_ENABLE: "1"
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=yes idekey=PHPSTORM"
      XDEBUG_SESSION: "PHPSTORM"
    ports:
      - mode: host
        target: 8080
        published: 38080
        protocol: tcp
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: volume
        source: composer_cache
        target: /var/cache/composer
volumes:
  composer_cache:
    driver: local
    name: global_composer_cache
