version: "3.9"
services:
  app:
    environment:
      NGINX_ACCESS_LOG: "/app/logs/nginx.access.log"
      NGINX_ERROR_LOG: "/app/logs/nginx.error.log"
      FPM_ACCESS_LOG: "/app/logs/php-fpm.access.log"
      FPM_ERROR_LOG: "/app/logs/php-fpm.error.log"
      PHP_ERROR_LOG: "/app/logs/php.error.log"
      XDEBUG_OUTPUT_DIR: "/app/logs"
      OPCACHE_ENABLE: "off"
      XDEBUG_ENABLE: "1"
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=yes idekey=PHPSTORM"
      XDEBUG_SESSION: "PHPSTORM"
    ports:
      - mode: host
        target: 8080
        published: 38080
        protocol: tcp
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: volume
        source: composer_cache
        target: /var/cache/composer
volumes:
  composer_cache:
    driver: local
    name: global_composer_cache
