version: "3.8"
services:
  base_image:

  app:
    environment:
      OPCACHE_ENABLE: "off"
      XDEBUG_ENABLE: "on"
      XDEBUG_REMOTE_AUTOSTART: "off"
      XDEBUG_REMOTE_CONNECT_BACK: "on"
      XDEBUG_REMOTE_HOST: ""
      XDEBUG_REMOTE_PORT: "9000"
      XDEBUG_IDE_KEY: "DOCKER"
      APP_ENV: "development"
    ports:
      - mode: host
        target: 8080
        published: 38080
        protocol: tcp
      - mode: host
        target: 9000
        published: 39000
        protocol: tcp
    volumes:
      - type: volume
        source: composer_cache
        target: /var/cache/composer
      - type: bind
        source: ./app
        target: /app

volumes:
  composer_cache:
    name: global_composer_cache
