apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpdock
spec:
  selector:
    matchLabels: {} # use kustomize commonLabels
  template:
    metadata:
      labels: {} # use kustomize commonLabels
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "http"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: http-server
          image: ghcr.io/damlys/phpdock
          envFrom:
            - configMapRef:
                name: phpdock
            - secretRef:
                name: phpdock
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /ready
          livenessProbe:
            httpGet:
              port: http
              path: /healthy
          resources:
            requests:
              cpu: 100m
              memory: 128M
            limits:
              cpu: 200m
              memory: 256M
