apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpdock
spec:
  template:
    spec:
      containers:
        - name: http-server
          securityContext:
            runAsUser: 0
            runAsGroup: 0
