services:
  rte:
    build:
      context: .
      dockerfile: Dockerfile
      target: rte
    image: damlys/phpdock-env:rte-0.0.0

  sdk:
    build:
      context: .
      dockerfile: Dockerfile
      target: sdk
    image: damlys/phpdock-env:sdk-0.0.0
