name: Continuous Delivery
on:
  push:
    branches:
      - develop
      - master
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"
jobs:
  job0:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        run: docker login --username="damlys" --password="${{ secrets.DOCKER_TOKEN }}"
      - name: Set Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Clone Git repository
        uses: actions/checkout@v2

      - name: Install NPM modules
        run: npm install
      - if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        name: Bump version (prerelease)
        run: npm run bump-version:prerelease
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Bump version (release)
        run: npm run bump-version:release

      - name: Build Docker images
        run: docker-compose build

      - name: Copy docker-compose.override.yml
        run: cp ./.github/docker-compose.override.yml ./docker-compose.override.yml
      - name: Run Docker containers
        run: docker-compose up --detach
      - name: Wait 10s
        run: sleep 10
      - name: Run unit tests
        run: docker-compose exec -T app composer run-script unit-tests
      - name: Run HTTP API tests
        run: docker-compose exec -T app composer run-script http-api-tests
      - name: Destroy Docker containers
        run: docker-compose down --volumes --remove-orphans

      - if: github.event_name == 'push'
        name: Publish Docker images
        run: docker-compose push
      - if: github.event_name == 'push'
        name: Publish version
        run: git push && git push --tags
